{{- define "cache" -}}
// Code generated by muxi curd. DO NOT EDIT.

package {{.PackageName}}

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/muxi-Infra/muxi-micro/pkg/logger"
	"github.com/redis/go-redis/v9"
)

// 序列化
func UnMarshalJSON_{{.ModelName}} (s string, model *{{.ModelName}}) error {
    return json.Unmarshal([]byte(s), model)
}

func UnMarshalString_{{.ModelName}} (s string, model *[]int64) error {
    return json.Unmarshal([]byte(s), model)
}

func MarshalJSON_{{.ModelName}}(model *{{.ModelName}}) (string, error) {
	val, err := json.Marshal(model)
	if err != nil {
		return "", err
	}
	return string(val), nil
}

func MarshalString_{{.ModelName}}(model *[]int64) (string, error) {
	val, err := json.Marshal(model)
	if err != nil {
		return "", err
	}
	return string(val), nil
}

// cache
func (u *{{.ModelName}}Exec) DelCache(ctx context.Context, model *{{.ModelName}}) {
	err := u.cache.Del(ctx, fmt.Sprintf("%s%v", cache{{.ModelName}}{{.Pr}}Prefix, model.{{.Pr}})).Err()
	if err != nil {
	    u.logger.Warn("主键缓存删除失败", logger.Field{"{{.Pr}}": model.{{.Pr}}, "error": err})
	}
	{{- $outer := . -}}
    {{- range $notpr := .NotPrs}}
    err = u.cache.Del(ctx, fmt.Sprintf("%s%v", cache{{$outer.ModelName}}{{$notpr.Name}}Prefix, model.{{$notpr.Name}})).Err()
    if err != nil {
        u.logger.Warn("非主键缓存删除失败", logger.Field{"{{$notpr.Name}}": model.{{$notpr.Name}}, "error": err})
    }
    {{- end}}
}

func (u *{{.ModelName}}Exec) Get(ctx context.Context, cachestr string) *{{.ModelName}} {
	var data {{.ModelName}}
	cacheval, err := u.cache.Get(ctx, cachestr).Result()
	if err == nil {
		err := UnMarshalJSON_{{.ModelName}}(cacheval, &data)
		if err != nil {
			u.logger.Warn("Json 序列化出错", logger.Field{"error": err})
			return nil
		}
		return &data
	}
	if !errors.Is(err, redis.Nil) {
		u.logger.Warn("主键缓存获取失败", logger.Field{"error": err})
		return nil
	}
	return nil
}

func (u *{{.ModelName}}Exec) GetMany(ctx context.Context, cachestr string) *[]{{.ModelName}} {
	var datas []{{.ModelName}}
	cacheval, err := u.cache.Get(ctx, cachestr).Result()
	if err == nil {
		var key []int64
		err := UnMarshalString_{{.ModelName}}(cacheval, &key)
		if err != nil {
			u.logger.Warn("Json 序列化出错", logger.Field{"error": err})
			return nil
		}
		for _, c := range key {
			data, err := u.FindOne(ctx, c)
			if err != nil {
				return nil
			}
			datas = append(datas, *data)
		}
		return &datas
	}
	if !errors.Is(err, redis.Nil) {
		u.logger.Warn("非主键缓存获取失败", logger.Field{"error": err})
		return nil
	}
	return nil
}

func (u *{{.ModelName}}Exec) Set(cachestr string, data *{{.ModelName}}) {
	str, err := MarshalJSON_{{.ModelName}}(data)
	if err != nil {
		u.logger.Warn("Json 序列化出错", logger.Field{"error": err})
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), u.setTTL)
	err = u.cache.Set(ctx, cachestr, str, u.expiration).Err()
	if err != nil {
		u.logger.Warn("主键缓存设置失败", logger.Field{"error": err})
	}
	cancel()
}

func (u *{{.ModelName}}Exec) SetMany(cachestr string, data *[]{{.ModelName}}) {
	ctx, cancel := context.WithTimeout(context.Background(), u.setTTL)
	defer cancel()

	var key []int64
	for _, v := range *data {
		key = append(key, v.{{.Pr}})
		cachestr2 := fmt.Sprintf("%s%v", cache{{.ModelName}}{{.Pr}}Prefix, v.{{.Pr}})
		u.Set(cachestr2, &v)
	}
	str, err := MarshalString_{{.ModelName}}(&key)
	if err != nil {
		u.logger.Warn("Json 序列化出错", logger.Field{"error": err})
		return
	}
	err = u.cache.Set(ctx, cachestr, str, u.expiration).Err()
	if err != nil {
		u.logger.Warn("非主键缓存设置失败", logger.Field{"error": err})
	}
}

{{- end -}}