{{- define "header" -}}
// Code generated by muxi curd. DO NOT EDIT.

package {{.PackageName}}

import (
    "context"
    "fmt"

    "github.com/muxi-Infra/muxi-micro/pkg/logger"
    "github.com/redis/go-redis/v9"
    "gorm.io/gorm"
)

const (
    {{- range $field := .Fields}}
    cache{{$.ModelName}}{{$field.Name}}Prefix = "cache:{{$.ModelName}}:{{$field.Name}}:"
    {{- end}}
)

type {{.ModelName}}Model interface {
    Create(context.Context, *{{.ModelName}}) error
    FindOne(context.Context, int64) (*{{.ModelName}}, error)
    {{- range $notPr := .NotPrs}}
    FindBy{{$notPr.Name}}(context.Context, {{$notPr.Type}}) (*[]{{$.ModelName}}, error)
    {{- end}}
    Update(context.Context, *{{.ModelName}}) error
    Delete(context.Context, int64) error
}

type {{.ModelName}}Exec struct {
    db     *gorm.DB
    cache  *redis.Client
    setTTL time.Duration
    expiration time.Duration
    logger logger.Logger
}

func New{{.ModelName}}Model(db *gorm.DB, cache *redis.Client, setTTL, expiration time.Duration, logger logger.Logger) *{{.ModelName}}Exec {
	return &{{.ModelName}}Exec{
		db:     db,
		cache:  cache,
		setTTL: setTTL,
		expiration: expiration,
		logger: logger,
	}
}

{{template "db" $}}

{{- end -}}