{{- define "header" -}}
// Code generated by muxi curd. DO NOT EDIT.

package {{.PackageName}}

import (
    "context"
    "github.com/muxi-Infra/muxi-micro/pkg/sql"
    "gorm.io/gorm"
)

type {{.ModelName}}Model interface {
    Create(ctx context.Context, data *{{.ModelName}}) error
    FindOne(ctx context.Context, id int64) (*{{.ModelName}}, error)
    {{- range $notPr := .NotPrs}}
    FindBy{{$notPr.Name}}(ctx context.Context, {{$notPr.Name}} {{$notPr.Type}}) (*[]{{$.ModelName}}, error)
    {{- end}}
    Update(ctx context.Context, data *{{.ModelName}}) error
    Delete(ctx context.Context, id int64) error
}

type {{.ModelName}}Exec struct {
    exec      *sql.Execute
}

func New{{.ModelName}}Model(db *gorm.DB) *{{.ModelName}}Exec {
    exec := sql.NewExecute(db)
    return &{{.ModelName}}Exec{
        exec:      exec,
    }
}

{{template "db2" $}}

{{- end -}}