{{- define "header" -}}
// Code generated by muxi curd. DO NOT EDIT.

package {{.PackageName}}

import (
    "context"
    "gorm.io/gorm"
)

type {{.ModelName}}Model interface {
    Create(context.Context, *{{.ModelName}}) error
    FindOne(context.Context, int64) (*{{.ModelName}}, error)
    {{- range $notPr := .NotPrs}}
    FindBy{{$notPr.Name}}(context.Context, {{$notPr.Type}}) (*[]{{$.ModelName}}, error)
    {{- end}}
    Update(context.Context, *{{.ModelName}}) error
    Delete(context.Context, int64) error
}

type {{.ModelName}}Exec struct {
    db *gorm.DB
}

func New{{.ModelName}}Model(db *gorm.DB) *{{.ModelName}}Exec {
    return &{{.ModelName}}Exec {
    	db: db,
    }
}

{{template "db2" $}}

{{- end -}}